### PR TITLE
en translations for alerts (new line break in calculator removed)

### PR DESCRIPTION
**Pull request by scibuff**
image

^^ removed

### CODE REVIEW

**Comment by andrgin** [comment]
Why do you want a line break? It fits perfectly without one making the box smaller.

**Comment by scibuff** [comment]
1) seems tidier with the break
2) i think there needs to be some sort of a separator (could be a comma I guess as well)
3) not sure if the line is wide enough for all translations

**Comment by scibuff** [comment]
I've removed the new line break in the calculator. Thanks

**Comment by scibuff** [comment]
@andrgin I've removed the new line break in the calculator. Thanks

**Pull request merged**
