### PR TITLE
New feature: Alerts

### PR DESCRIPTION
**Pull request by scibuff**
FoE-Helper Alerts use the browser Notifications API to display desktop notifications (within the OS notification center). Players can set alerts based on game events (auctions, battlegrounds, collections, plundering etc) and be notified when it is time to act on them. 

The advantage of using the native OS notifications is that players will be notified even when they use different applications while the game is running (as long as the game remains open in the browser and the application they use is not in full screen mode [e.g. watching a movie]). 

First, the desktop notifications have to be enabled. There is a UI provided for granting notification permissions.

image

image

image

image

image

Once the permissions have been granted new alerts can be created, existing alerts can be modified and deleted. 

image

image

image

image

For now, most alerts/notification need to be created manually. Currently, the only preset alerts (with the correct time provided by the plugin) are:
- The end of an auction at the Antiques Dealer
- The end of a trade (exchange) at the Antiques Dealer
- Guild Battleground sector unlock times (these are available only after the GBG has been loaded)

More automation is coming in the next release, which may include:

- Automatically creating a new alert when the player make a bid at the Antiques Dealer auction (with the correct time, e.g. 60 seconds before the auction ends)
- An instant alert when there is a lot of activity in the Guild Battlegrounds (for example, 10 fights at a sector in 5 seconds). Please note that this will work _only_ when the Battlegrounds are open in game!
- Main Menu countdown = a countdown to the next alert as an overlay over the main menu icon
- and others ...

image

### CODE REVIEW

**Comment by dsiekiera** [comment]
@scibuff 
Very nice tool! That's exactly how we started. We just didn't have a GUI that you wrote now. Wonderful!

But. We thought a little further. The timer itself is managed by background.js. This means that the game does not have to be open and all timers of all worlds are monitored at the same time. Furthermore, we store the timers on foe-rechner.de in the database, which enables us to send emails and later to set push notifications in the app (Android).

We would now customize your module and split it into a GUI and a background process.

What do you say?

**Comment by scibuff** [comment]
Brilliant. That's what I thought of doing next! Just let me know what you'd like me to do...

**Comment by dsiekiera** [comment]
Then we take over the module now.

In the next step we would establish the communication between background.js and DB and write the communication between background and extension frontend.

**Comment by scibuff** [comment]
Sounds good! Thanks

**Pull request merged**
