### PR TITLE
Update nl.json

### PR DESCRIPTION
**Pull request by Beta-Wolf**
not completed yet

### CODE REVIEW

**Comment by andrgin** [comment]
Please remove the "//Todo: Translate" after translating. Otherwise our code generation tool will restore the English translation.

**Comment by Beta-Wolf** [comment]
Euhm, so how can I highlight translations I'm not sure of?

**Comment by osv** [comment]
@Beta-Wolf  remove  "//Todo: Translate" only where you finish translating to NL language. Dont remove where still english translation.

**Comment by Beta-Wolf** [comment]
Yeah, but I'm not completely sure of all of my translations. Cause some have multiple meanings and I'm missing the context.
So I would like to highlight those translation so I can check them again later.
Cause previously, I just didn't delete //To do Translate, only when I'm very sire my translation is correct.

**Comment by andrgin** [comment]
If you do not remove the Todo: Translate our code generating tool will replace your translation with the English one on the next run, so you should either:
.) Translate a text and remove the // Todo: Translate
.) Do not translate it if you are not sure and leave the // Todo: Translate

I think the best is that you just translate it as good as you can and if you notice the translation was not good you can change it again.

**Comment by Beta-Wolf** [comment]
Can I change it to // Translation not certain?

Or will that also affect stuff?

**Comment by andrgin** [comment]
Sorry, but any other comment except from the //Todo: Translate will break the file and prevent loading

**Comment by Beta-Wolf** [comment]
Oke

**Comment by andrgin** [comment]
I am closing this pull request. Please create a new one if the comments have been corrected.

**Pull request closed without merging**
