### PR TITLE
Graphics for FP stock (and buyable) + infoboard minor fix

### PR DESCRIPTION
**Pull request by scibuff**
This update added styles to the FP stock and FP buyable as well as fixes the position for smaller screens

image

image

image

Fixes an issue with the `Infoboard` where it would show the incorrect amount of gained FPs when no FPs have been gained (e.g. slot 6 and "lower").

Also, added a new alert option to create an alert for each locked Guild Battleground sector 

image

image

### CODE REVIEW

**Comment by andrgin** [comment]
I dont think the styles for FP stock is a good idea. This looks exactly like the ingame fields. Many players will think this is an ingame display and will report bugs with it to Inno instead of us, which already was problem in the past.

**Comment by scibuff** [comment]
@andrgin I see, would this work ?

image

**Comment by andrgin** [comment]
Still looks very similar to me

**Comment by scibuff** [comment]
@andrgin ok, this should be clear now

image

image

image

**Comment by dsiekiera** [comment]
Yes, this looks well. Thanks!

**Pull request merged**
