### PR TITLE
Beta

### PR DESCRIPTION
**Pull request by Cdemir58**
Übersetzun in Türkisch für FOE-Helper

inhalt derZip ist tr.json 

[tr.zip](https://github.com/dsiekiera/foe-helfer-extension/files/4551957/tr.zip)

### CODE REVIEW

**Comment by andrgin** [comment]
What are you guys trying to do here?

**Comment by osv** [comment]
I also dont understand :)

**Comment by scibuff** [comment]
I think the OP wanted to add tr.json but grabbed everything from beta

**Comment by osv** [comment]
right... let me try add it...

**Comment by osv** [comment]
will create another PR

**Pull request closed without merging**
